### ISSUE TITLE
Can't find process rate coefficient

### ISSUE THREAD

**Issue by Hyguys** [soerenweinrich/ADM1#1]
Hello Sir. My name is Leandro and I am a undergraduate Chemical Engineering student. Just recently stumbled upon your work and simplification of ADM1 model. Truly, an work of art and probably will revolutionize ADM1 studies.

I'm trying to understand, more deeply, how the equations were implemented, and couldn't understand 2 things:

1) Where are, in any of the models, the disintegration process? It is said in the article that "kinetic effects related to disintegration of particulate composites (kdis) are assigned to the first-order hydrolysis constants of carbohydrates, proteins and lipids (kch, kpr and kli)." However, how can this be, given that the first-order hydrolysis constants were maintained the same?

2)  In any of the ADM1 models presented: could you give an more detailed explanation of where did you get the process rate coefficients? for example, consider the ADM1-R4 process equations
`process(1) =  0.24819 * rate(1) +  0.32208 * rate(2) +  0.63928 * rate(3) - rate(5); `
Can you explain how to obtain the 0.24819, 0.32208, 0.63928 and -1 coefficients? And how are they related to f and Y coefficients.

Kind regards,

**Comment by soerenweinrich** [comment]
Dear Leandro,

thanks for your interest in our research!

You can find my answers to both your questions below.

1. Generally, disintegration or hydrolysis constants are typically adjusted during model application. Thus, standard values are  just rough estimates or initial values for numerical parameter estimation. Additionally, first-order disintegration or hydrolysis functions are just empirical expressions that reflect cumulative effects of all microscopic processes occurring in the digester. For mesophilic anaerobic digestion (AD) of homogeneous substrates the ADM1 originally recommends to only estimate the single first-order disintegration rate constant (k<sub>dis</sub>), while neglecting hydrolysis rate by using fast first-order hydrolysis constants (k<sub>ch</sub> = k<sub>pr</sub> = k<sub>li</sub> =10 d<sup>-1</sup>). As we simulate AD processes operated with numerous agricultural substrates (lignocellulosic biomass) and wastes with different compositions of carbohydrates, proteins and lipids, we typically estimate individual hydrolysis constants and neglect the disintegration rate by assuming a fast first-order disintegration constant (k<sub>dis</sub> = 10 d<sup>-1</sup>). Furthermore, practical identifiability of disintegration and hydrolysis parameters has to be questioned, as shown in Figure 3 of the publication on [model application](https://doi.org/10.1016/j.biortech.2021.125104). Thus, there are probably multiple combinations of individual hydrolysis and/or disintegration parameters, which in the end will yield similar simulation results of available measurements.
2. The rate coefficients were derived based on stoichiometric calculations described in the publication on [model development](https://doi.org/10.1016/j.biortech.2021.125124). Thus, we applied original standard parameter values for f and Y, but transferred them to a mass-based reference unit and then combined individual processes based on sum reactions as described in equation 1 of the publication. For the original mass-based ADM1 you can find the [Petersen matrices](https://github.com/soerenweinrich/ADM1/blob/main/Documents/Weinrich_2021_Model_structures.pdf) for different versions (e.g., for variable f and Y coefficients) in the additional document on GitHub. Thus, all (new) rate coefficients are based on the original stoichiometry of the COD-based ADM1.


Hope this helps. If you have any further questions, just let me know!

Best regards,
Sören
